name: PipeCatFlowEditor
description: "Утилита для визуального отображения и редактирования диалогов PipeCat Flows"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  permission_handler:
  http: ^1.4.0
  provider: ^6.1.5
  markdown_widget: ^2.3.2+8
  vector_math: ^2.1.0
  flutter_code_editor: ^0.3.5
  a_star_algorithm: ^0.4.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  file_picker: ^10.3.3
  window_manager: ^0.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/